# Generated by Django 5.2.4 on 2025-08-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default=1, upload_to='imagens'),
            preserve_default=False,
        ),
    ]
